# apiVersion: v1
# kind: Pod
# metadata:
#   name: acolhedores
# spec:
#   containers:
#   - name: acolhedores
#     image: gibenuthe/acolhedores:0.0.1

# FOI USADO PARA A CRIAÇÃO DO POD, AGORA É DESNECESSÁRIO.
