#deployments vem de apps/v1
apiVersion: apps/v1
#tipo
kind: Deployment
metadata:
  #nome do deployment
  name: acolhedores-deployment
spec:
  #quantas cópias
  replicas: 1
  #para especificar o rótulo
  selector:
    matchLabels:
    #rótulo, app não tem nada de especial, pode ser qq coisa
    #Deployment vai selecionar todo Pod que tiver esse rótulo
      app: acolhedores
  #modelo que vai ser usado para construção dos Pods
  template:
    metadata:
      labels:
        #os Pods terão esse rótulo, assim,
        #serão selecionados por esse deployment
        app: acolhedores
    spec:
      containers:
      - name: acolhedores
        image: gibenuthe/acolhedores:0.0.1
        ports:
        - containerPort: 80
