#alpine: imagem Linux "pequena"
FROM node:14

# Create an application directory
RUN mkdir -p /app

 # um diretório no sistema de arquivos do contêiner para os

WORKDIR /app

 #copia o arquivo package.json para poder executar npm

COPY package.json .

 #instala as dependências
RUN npm install

 #copia todo o conteúdo .local para a imagem
COPY . .

# EXPOSE 8080

 #executa quando o contêiner entrar em execução
CMD ["npm", "start"]
